spring.application.name=staff-service
server.port=8090

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3310/db_polisport_staff?createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.jpa.show-sql=true

spring.docker.compose.enabled=false

