spring.application.name=staff-service
server.port=8090

spring.datasource.url=jdbc:mysql://db-staff:3306/polisport_staff_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.jpa.show-sql=false

spring.docker.compose.enabled=false
spring.jpa.open-in-view=true

spring.main.web-application-type=servlet

# Swagger/OpenAPI Configuration
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.enabled=true
