spring.application.name=atletas-service
server.port=8080

# Apunta directo al servicio de Docker. Como usas alias en el yaml, db-mysql o db-atletas te funcionaran segun tu red.
spring.datasource.url=jdbc:mysql://db-atletas:3306/polisport_atletas_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.jpa.show-sql=false

# FUERA DOCKER (Desactiva la gestion automatica desde codigo, ya que usas el CLI de Docker)
spring.docker.compose.enabled=false
spring.jpa.open-in-view=false