spring.datasource.url=jdbc:mysql://localhost:3306/polisport_salud
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#desactiva docker
spring.docker.compose.enabled=false
#activa flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
#puerto utilizado
server.port=8089