spring.application.name=entrenamiento-service
server.port=8085

# Conexion directa al contenedor db-entrenamientos mapeado en el docker-compose
spring.datasource.url=jdbc:mysql://db-entrenamientos:3306/polisport_entrenamientos_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.jpa.show-sql=false

spring.docker.compose.enabled=false
spring.jpa.open-in-view=false

spring.main.web-application-type=servlet

# Swagger/OpenAPI Configuration
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.enabled=true