spring:
  application:
    name: entrenamiento-service
  datasource:
    url: jdbc:mysql://db-entrenamientos:3306/polisport_entrenamientos_db?useSSL=false&serverTimezone=UTC
    username: root
    password: ""
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
  flyway:
    enabled: true
  docker:
    compose:
      enabled: false
  main:
    web-application-type: servlet

server:
  port: 8085

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /api-docs
