spring.application.name=staff-service
server.port=8089
# Docker Compose - Disable if not installed
spring.docker.compose.enabled=false

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/db_staff
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Flyway Configuration
spring.flyway.enabled=true
spring.flyway.baselineOnMigrate=true
spring.flyway.locations=classpath:db/migration


