spring.application.name=iam-service
server.port=8080

spring.datasource.url=jdbc:mysql://db-iam:3306/polisport_iam_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.jpa.show-sql=false

spring.docker.compose.enabled=false
spring.jpa.open-in-view=true
