spring.application.name=salud-service
server.port=8080

# Conexion al contenedor db-salud dentro de Docker
spring.datasource.url=jdbc:mysql://db-salud:3306/polisport_salud_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.jpa.show-sql=false

spring.docker.compose.enabled=false
spring.jpa.open-in-view=false